variable "service_name" {
  type=string
  description="ECS service to build and deploy to"
}
variable "cluster_name" {
  description="ECS cluster to deploy to"
}
/**
to move buildspec.yml into application sources
*/
variable "path_2_buildspec" {
  type=string
  description="path to build spec file, resolvable at deploytime by terraform."
  default="buildspec.yml"
}

variable "vcs_repo_name" {
  description="GIT repo name"
}
variable "vcs_repo_owner"{
  description="Github repo owner"
}
variable "vcs_repo_type" {
  type=string
  description="valid values: GITHUB, GITHUB_ENTERPRISE"
  default="GITHUB"
}

variable "aws_resource_base_name" {
  type="string"
  description="prefix for autogenerated names of AWS assets"
}
variable "ecr_registry_id" {
  description="registry_id of ECR repo to hold docker images in"
}
variable "ecr_repository_url" {
  description="full url of ECR repo to hold docker images in"
}

variable "app_container_name" {
  description="name of ECS container to deploy to"
}
variable "tags" {
  type=map(string)
  description="tags to be added to resources created by the module"
}
